name = "PkgTest3"
uuid = "6d9e3464-9911-40ef-92de-f3f4c1b9f41b"
authors = ["Ferdinand Rieck <ferdinand.rieck@smail.emt.h-brs.de>"]
version = "0.1.0"

[compat]
julia = "1.8.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
